### ISSUE TITLE
BUG: spatialite does not load (for me) when reading gpkg files

### ISSUE THREAD

**Issue by david-morris** [geofileops/geofileops#572]
I have an app which manipulates gpkg files where I was using `union()` and when using `subdivide_coords`!=0, it crashes because it can't find the ST_NPoints function.  

Indeed, `execute_sql(some_gpkg_filename, "SELECT spatialite_version();")` returns None.

What could be stopping geofileops from loading spatialite?  How does it make sense to document this, if this is a known issue?  If not, what could I do to help get this in a reproducible state?

**Comment by theroggy** [comment]
How did you install geofileops and its dependencies?

It's very recommended to use conda... as some dependencies are not trivial to install in another way... and to be honest, I don't have any experience installing those dependencies not using conda...

**Comment by chris-stetter** [comment]
We cannot install it using conda. We have a custom docker image, so install it manually. Are there any specific versions of dependencies required for this to work?

**Comment by theroggy** [comment]
OK. I suppose the problem is that you don't include spatialite in your image.

Most (sample) [docker images provided by gdal](https://github.com/OSGeo/gdal/tree/master/docker) include spatialite, only alpine-small doesn't. Probably you can get some inspiration there on how to include spatialite in your image?

Regarding minimal versions... spatialite has been supported by gdal forever, but recommended minimal versions for geofileops can be found [here](https://github.com/geofileops/geofileops/blob/main/ci/envs/minimal.yml), as there have been several bug fixes in gdal through the years that fixed things that were triggered in geofileops.

**Comment by david-morris** [comment]
Thanks for the quick response!  We were confused because from the spatialite prompt, we could use spatialite functions in the same image. 
It looks like the root cause was a GDAL version mismatch between the direct dependency and the pyogrio dependency.  So the version the direct dependency was expecting wasn't installed.

Would you say that's out of scope for this project or does it make sense to try to adjust how the package is versioned and/or generate warnings at some point?

**Comment by chris-stetter** [comment]
This solved the problem: `pyogrio==0.8.0 --no-binary pyogrio`.

**Comment by theroggy** [comment]
> Thanks for the quick response! We were confused because from the spatialite prompt, we could use spatialite functions in the same image. It looks like the root cause was a GDAL version mismatch between the direct dependency and the pyogrio dependency. So the version the direct dependency was expecting wasn't installed.
> Would you say that's out of scope for this project or does it make sense to try to adjust how the package is versioned and/or generate warnings at some point?

In the past there have been some "pre-flight checks" in geofileops to check the environment for some version-specific problems, but they were removed when support for the version of gdal and spatialite that triggered them were dropped. But no problem, or even a good idea, to reintroduce some checks.

I don't think is is possible/easy to validate if the gdal version needed for bindings are available, but maybe e.g. just testing if `execute_sql(some_gpkg_filename, "SELECT spatialite_version();")` returns something expected and writing a warning if not would already be useful as an early warning that something fishy is about?

**Comment by theroggy** [comment]
@david-morris @chris-stetter I added some tests when geofileops is imported that gives warnings if `spatialite` is not available in one of the 3 ways spatialite is used in geofileops + added some info in the installation instructions.

I wasn't able to tests it though...

Feedback is welcome...
https://github.com/geofileops/geofileops/pull/573
